analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f564b'
    - '#ffa5bc'
    - '#768f75'
  brandStrength: 0
  lightness: 0.6875
  rhythmicContrast: 1
  saturation: 0.875
cta: {}
layout_spectrum: 0.643018
name: Disciples Make Disciples
opengraph: {}
purpose: []
typography_spectrum: 0.81673
