typography_spectrum: 0.81673
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#d2d2d2'
    - '#353535'
    - '#9e6a64'
    - '#f68fa4'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.16231
analytics: {}
author:
  name: ''
  url: ''
  email: ''
name: Disciples Making Disciples
cta: {}
navigation:
  - name: Subscribe to Updates
    id: a3e40d31-5ee8-4534-a94c-b424c9b57bfc
    type: content
title: Disciples Making Disciples
purpose: []
