typography_spectrum: 0.6352411701809615
content_rating:
  adult: false
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.029040309134870768
  lightness: 0.716714505571872
  saturation: 0.20494724507443607
  rhythmicContrast: 0.2797303097322583
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.2896104920655489
analytics: {}
author:
  name: Elijah Peters
  url: ''
  email: Elijah@dmd.org.nz
name: Disciples Making Disciples
cta: {}
navigation:
  - name: About
    id: d8d1faaa-8ea5-465e-a563-f4d6a8a2285c
    type: content
  - name: Subscribe to Updates
    id: a3e40d31-5ee8-4534-a94c-b424c9b57bfc
    type: content
  - name: Register for DMD 2016
    url: dmdconference2016.eventbrite.co.nz
    type: external
title: Disciples Making Disciples
description: BE • MAKE • SEND
purpose: []
