name: Disciples Making Disciples
favicon: null
layout_spectrum: 0.4267
typography_spectrum: 0.81673
title: Disciples Making Disciples
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f564b'
    - '#ffa5bc'
    - '#768f75'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
