name: Disciples Making Disciples
layout_spectrum: 0.16231
typography_spectrum: 0.81673
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#000000'
    - '#d2d2d2'
    - '#353535'
    - '#9e6a64'
    - '#f68fa4'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
title: Disciples Making Disciples
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
