name: Disciples Making Disciples
favicon: null
layout_spectrum: 0.65331
typography_spectrum: 0.81673
title: Disciples Making Disciples
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d2d2d2'
    - '#353535'
    - '#9e6a64'
    - '#f68fa4'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
